### ISSUE TITLE
[Feature] Support `WinUI` and `MacOS` (MAUI)

### ISSUE THREAD

**Issue by AndreasReitberger** [oscoreio/Maui.Biometric#2]
Thanks for providing this project :)

This is actually not a bug.  I want to use this project to secure a maui application. 
It seems to support Android and iOS, but not WinUI / macOS (macOS maybe works with fingerprint?).
Maybe it is possible to prompt for the user password if on `Windows` or `macOS`

Chrome does it this way, if entering the saved passwords. Is this something you can think about?

**Comment by HavenDV** [comment]
Hello. Do you mean net8.0-macos TargetFramework?
Because otherwise it's a bug because net8.0-maccatalyst/net8.0-windows are supported and should work completely
